language: node_js
node_js:
- 11.11.0
script:
- npm i
- cd client
- npm i
- npm run build
- cd ..
- npm run build:server
after_script:
- rimraf node_modules
- rimraf node_modules --prefix client
deploy:
  provider: heroku
  api_key:
    secure: s2MnMy1ELSCb0hDHaG5hKnntmnM4boXsdznLwBt5tvrdtMHIbi1B/sU12KITbmAeQwMln+iJM+UjvTW2vizLKnEaJFP3wUdfixY8VOE1/JeFQosR9WVCzxJKvy/VjciQs/Xe3nIBeLi9ttmuIAmoCXBFu/rHufyvYBWTKO/eet2PHT7xVyNzqbZS/JXkXubUUhAVH+YZBmq00rSdRfx/uQpGsrakJMTrB87+B3SfFxt6+S2ZRrR2iH2vg3TDe7e44R91lnZXSnONYv9SFt4kO5P6dIjKYxhhn0BsAKi8RutpVlL9vaeIO+PgWVv4MTgbDzqPjXZ5/mAMYFUoay8EjLx6JUmfWXUF06qNVXcr/YyecI7vyjYO+d5BF6exulf7/toZRLAZOMDZUvgaeBTc6QIX11trpkv7SOJPk8x6a7YUEai9VcJzv2wPBgxICLevVjalZuZ8XonHGRQPEwkChd9bsvJnjqNXvOmL+vLpBLeJXu2z8eXj8zKv2Okn0lkAbDXQC1n/CbpbK92BshNPnd//y9Cq3ivGXjuku+lpb+YlfYz2M2Sb1LwPn+TVd2cu3/gdCnumvTgU0Di5CtB/dbzYS/vMzyF9rfw8WyEGe3PCA15pQs36cg21z5AL5tourazYdcKEsbeqyLn6jA0GlznbC4gppDf8c1n3pS27f4g=
  skip_cleanup: true
  app:
    master: supportyourlocal-prod
    develop: supportyourlocal-dev
  on:
    repo: wsoeltz/supportyourlocal
